### ISSUE TITLE
Improve UX - Modern CLI

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#10]
There are lots of nice CLI tools out there. Need to do some research to find out what they do best and what users like about them to make sure we offer the best possible experience.

**Comment by jimaek** [comment]
Its somewhat vague I know, just maybe use your experience and look into what others do to make their CLI UX good and what we could implement ourselves.
A good starting point: 
- https://github.com/httpie/httpie
- https://charm.sh/

Maybe try to start by solving specific problems with our CLI? e.g. try to use Globalping CLI to figure out how your website performs from different regions. And then see what would make the experience faster or easier?

**Comment by jimaek** [comment]
@didil any ideas or we can close it?

**Comment by didil** [comment]
@jimaek no ideas at the moment. Ok for me to close it
