### ISSUE TITLE
History command unknown

### ISSUE THREAD

**Issue by inventarSarah** [jsdelivr/globalping-cli#101]
**Problem**
Using command
`globalping history`
 in the CLI returns 
`Error: unknown command "history" for "globalping"`

When running 
`globalping --help`
 the history command is not showing up in the "Additional commands" list.
```
Additional Commands: 
completion    Generate the autocompletion script for the specified shell                                  
help               Help about any command                                                                     
install-probe  Join the community powered Globalping platform by running a Docker container.               
version           Print the version number of Globalping CLI 
```

**My info**
- Tested in two places:
  - Used Powershell under Windows 10 (installed GP CLI with Chocolately)
  - Used WSL Ubuntu  (Version 22.04.4) under Windows 10 (installed GP CLI with apt)
- Globalping CLI version 1.2.1 in Windows and WSL

**Comment by MartinKolarik** [comment]
It was added after 1.2.1 and will be included in the next release. I was just looking at this yesterday 😄

**Comment by inventarSarah** [comment]
Ah, I see :) - thanks, Martin!
