### ISSUE TITLE
Linux package cloud publishing fails

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-cli#110]
Opening a new issue so that this doesn't get lost: https://github.com/jsdelivr/globalping-cli/pull/98#issuecomment-2174006257

I already [made a change](https://github.com/jsdelivr/globalping-cli/commit/22466d3575f09ce6bb5d6326985b6ca7de302f98) that I think might fix it, but @radulucut, please check whenever you have time.

**Comment by radulucut** [comment]
@MartinKolarik your changes (22466d3575f09ce6bb5d6326985b6ca7de302f98) should fixed the issue. Thanks

**Comment by MartinKolarik** [comment]
@jimaek in that case try to publish 1.3.1
