### ISSUE TITLE
Restore stdout/stderr handling

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-cli#117]
It seems that through some refactoring, we lost changes from #55 and #56. Let's restore them. Things that should go to `stderr`:
 - all lines starting with `>` (location info, share links, ...)
 - `This infinite ping will consume 1 API credit for every 16 packets until stopped.` message from #114
 - The initial line + all headers of `http --full` command (as in #55).
 - Error messages

**Comment by MartinKolarik** [comment]
It also seems like a good idea to refactor the handling of colored output. Right now, we have conditions like this all over the place:

```go
if r.ctx.CIMode {
	r.printer.Printf("> %s\n", e.Message)
} else {
	r.printer.Printf(r.printer.Color("> "+e.Message, view.ColorLightYellow) + "\n")
}
```

It seems easy to forget. Would be better if the `Color` function had a required bool param like `useColor` and would simply return the original string when called with `false`.

**Comment by radulucut** [comment]
@MartinKolarik, outputting to stderr will cause this behaviour: #94, are we ok with that?
Wouldn't make more sense to have a separate flag for this, i.e. `--noInfo`?

**Comment by MartinKolarik** [comment]
Do you mean it'll cause issues specifically with `less` or with the CI mode or piping in general?

**Comment by radulucut** [comment]
with `less`, it's unrelated to CI mode

**Comment by MartinKolarik** [comment]
Ok, I see. I most likely misunderstood that issue back then since the description said CI, and you didn't really describe the changes in the fix... I'll check this a little later.

**Comment by MartinKolarik** [comment]
@radulucut let's do this. It seems the previous behavior was in line with the idea from https://github.com/jsdelivr/globalping-cli/issues/56#issue-1685200265, and the other issue was just a misunderstanding.
