### ISSUE TITLE
Better UX for HTTP

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#13]
Instead of breaking the URL into parts we should parse it ourselves.

So something like this

`globalping http https://cdn.jsdelivr.net/npm/react/?query=3`

This removes the need for --path and --query

Protocol should also be automated, in the above example it should use HTTPS as protocol since that's what the user specified.

**Comment by MartinKolarik** [comment]
Port may be present in the url and should be parsed as well. I'm only not sure if we should remove all 4 options or keep them and allow them to override the values from the url.

**Comment by jimaek** [comment]
Indeed, port should also be auto-parsed. I think we should keep them and allow overrides, this way we could do this:

`globalping http https://cdn.jsdelivr.net:8080/npm/react/?query=3 --protocol HTTP2`
