### ISSUE TITLE
SSL  and CA problem 

### ISSUE THREAD

**Issue by PerfectLiang** [jsdelivr/globalping-cli#130]
Can we add free TLS config to avoid SSL and CA problem

func NewClient(config Config) Client {
	return &client{
		http: &http.Client{
			// Transport: &http.Transport{
			// 	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
			// },
			Timeout: 30 * time.Second,
		},
		apiURL:    config.APIURL,
		apiToken:  config.APIToken,
		userAgent: config.UserAgent,
		cache:     map[string]*CacheEntry{},
	}
}

**Comment by radulucut** [comment]
We'll add the option to set a custom http client through the config.

I think it would be a better idea to append the cert to the root CAs instead of using `InsecureSkipVerify`.

**Comment by PerfectLiang** [comment]
good idea, thx

**Comment by MartinKolarik** [comment]
@radulucut I'm not sure, is there anything we still need to do here? If yes, in what scenarios does it apply?

**Comment by radulucut** [comment]
This can be closed from our side. A custom http client can be set, since abf3b23, to avoid this issue.
