### ISSUE TITLE
Packagecloud serving old versions

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#136]
I need some help figuring out why Packagecloud seems to be stuck on 1.2.1

```
# apt list -a globalping
Listing... Done
globalping/jammy,now 1.2.1 amd64 [installed]
globalping/jammy 1.1.6 amd64
globalping/jammy 1.1.5 amd64
globalping/jammy 1.1.0 amd64
globalping/jammy 1.0.1 amd64
globalping/jammy 0.4.0 amd64
globalping/jammy 0.3.0 amd64
globalping/jammy 0.1.8 amd64
globalping/jammy 0.1.7~next amd64
globalping/jammy 0.1.6 amd64
globalping/jammy 0.1.5 amd64
globalping/jammy 0.1.3 amd64
```

https://share.perfstack.net/2024/10/TabTip_2024-10-05_11-36-52.png

Since 1.4 is tagged as `any/any` it should be available as an upgrade for all OS including mine "Ubuntu 22.04.5 LTS"

**Comment by jimaek** [comment]
I deleted a bunch of old releases from packagecloud and it's updating correctly, but no 1.4

```
apt list -a globalping
Listing... Done
globalping/jammy,now 1.2.1 amd64 [installed]
globalping/jammy 1.1.6 amd64
globalping/jammy 1.1.5 amd64
```

**Comment by radulucut** [comment]
It seems that the only way to work with `any` and `rpm_any` is to change the install script to fetch the config with the `os` and `dist` set to `any`, `any`, and `rpm_any`, `rpm_any`.

Are you able to change that config? so, at least the new installations will fetch from any.

These lines should be changed:

`deb`
```sh
...
  apt_config_url="https://packagecloud.io/install/repositories/jsdelivr/globalping/config_file.list?os=${os}&dist=${dist}&source=script"
...
```

`rpm`
```sh
...
  yum_repo_config_url="https://packagecloud.io/install/repositories/jsdelivr/globalping/config_file.repo?os=${os}&dist=${dist}&source=script"
...
```

**Comment by jimaek** [comment]
No not really possible unfortunately
