### ISSUE TITLE
Goreleaser upgrade

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#139]
Our releases are full of deprecation messages. We're on v4 with v6 being out since June. 

@radulucut Can you please review the upgrade instructions to get us to v6 and verify it works? https://github.com/goreleaser/goreleaser-action/releases

**Comment by MartinKolarik** [comment]
After the Slack auth updates please, we need those first.

**Comment by MartinKolarik** [comment]
A few more, please check (from https://github.com/jsdelivr/globalping-cli/actions/runs/11367887008/job/31621646304):

```
• only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
• DEPRECATED: snapshot.name_template should not be used anymore, check https://goreleaser.com/deprecations#snapshotnametemplate for more info
```
