### ISSUE TITLE
Check/Fix user agent version

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-cli#141]
When I run `globalping version` with one of the releases installed, it correctly outputs the version. But in our server logs, all I see is `globalping-cli/vdev`. Are we not setting the version in user agent correctly or are really most people using this directly from GitHub?

**Comment by MartinKolarik** [comment]
I can see requests coming in using `v1.2.1`, but nothing newer and then the `vdev`. Not sure if that's simply related to the recent publishing issues and many people use the GH version, or we broke something around that time.

**Comment by radulucut** [comment]
The code looks fine to me, can you get the latest binary, run a test and check the logs? (I've also ran a few tests with 1.4.0)
