### ISSUE TITLE
Add authentication docs

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#142]
Need to add a section to README and maybe the help screen too that explains the different auth methods. oath for normal use and env var for CI and scripting.
Anything else I'm missing?

**Comment by MartinKolarik** [comment]
It's already very long, so let's move the whole docs part to `docs/README.md`, add a list of contents with links at the top there, and in the main README link to that file.

**Comment by jimaek** [comment]
Is not that long. But we can add a few links to the header. I personally hate it when main information is not available on the home page.

**Comment by MartinKolarik** [comment]
Our README is much more than the main info. I generally like how detailed it is, but everything in the how-to-use section will be better when it's on its own with its own nav at the top and not mixed with the installs etc. In the main readme we can keep a single command with a link to the other file for more.

**Comment by jimaek** [comment]
The auth info is only a few sentences long, we can easily add it without any other changes. If later you plan going into the technical details of the implementation then sure, you can do that part in a separate doc. But the overview summary should be on the main readme
