### ISSUE TITLE
Install fails on ARM Debian

### ISSUE THREAD

**Issue by weradus** [jsdelivr/globalping-cli#146]
I followed the steps .......
---
root@debian-arm64-1:~# curl -s https://packagecloud.io/install/repositories/jsdelivr/globalping/script.deb.sh | sudo bash
apt install globalping
globalping --help

Detected operating system as debian/bookworm.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.6.1
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing 
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/jsdelivr_globalping.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/jsdelivr_globalping-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package globalping
-bash: globalping: command not found

**Comment by jimaek** [comment]
Looks like we're not uploading ARM binaries to packagecloud, we should definitely fix this. @radulucut please check
