### ISSUE TITLE
ARM64 packages not being uploaded to packagecloud despite workflow changes.

### ISSUE THREAD

**Issue by curtisrecords** [jsdelivr/globalping-cli#149]
The recent PR #147 added support for arm64 packages, but they are not appearing in packagecloud.

**Comment by jimaek** [comment]
Hey, we will make a release once https://github.com/jsdelivr/globalping-cli/pull/148 gets merged. Should be soon

**Comment by curtisrecords** [comment]
Thank you very much :D
I've been using globalping for a long time and it has been very useful to me 🎵
