### ISSUE TITLE
Disable real-time when using CI option

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#31]

**Comment by didil** [comment]
@jimaek what is "real-time" ?

**Comment by jimaek** [comment]
Sorry it's this option https://github.com/jsdelivr/globalping/blob/master/docs/measurement/schema/request.md#inprogressupdates

Makes the output look realtime

**Comment by jimaek** [comment]
Also note that it's probably broken until we redeploy the API sometime today
