### ISSUE TITLE
Enable real-time updates by default

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-cli#32]
After https://github.com/jsdelivr/globalping/issues/308

**Comment by didil** [comment]
I guess this must be implemented before #31 as there is no implementation of real time updates / "inProgressUpdates" in the cli for now

**Comment by jimaek** [comment]
They can be done at the same time.
The context is that we had realtime on by default for all tests, and now it has to be enabled using that option

**Comment by didil** [comment]
@jimaek when I try to test the API I get the error `"inProgressUpdates" is not allowed`
this is the test json request I used
```json
{
	"limit": 5,
	"locations": [
		{
			"magic": "USA"
		}
	],
	"type": "traceroute",
	"target": "cloudserversaustralia.com.au",
	"inProgressUpdates": false,
	"measurementOptions": {}
}
```

**Comment by jimaek** [comment]
Yeah we didn't deploy the fix yesterday:( 
We will get it working today. I'll let you know when. You could switch to something else in the meantime I think

**Comment by jimaek** [comment]
Fix deployed. Please test everything to make sure we have real-time on by default and it works correctly
