### ISSUE TITLE
Ensure all our guidelines are followed

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-cli#33]
https://github.com/jsdelivr/globalping/blob/master/docs/CLIENT_GUIDELINES.md

**Comment by didil** [comment]
@MartinKolarik the document mentions 

> If the status is in-progress, wait 1 second

At the moment in the CLI, we're only waiting 100 milliseconds, should I change that to 1 second ?

**Comment by jimaek** [comment]
Before changing please test locally different values in between. If there's no difference then set 1s but if a lower value results in a better user experience then let's consider that
