### ISSUE TITLE
Release new updates to Winget

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#4]

**Comment by ayuhito** [comment]
I think I want to hold off on this until goreleaser/goreleaser#1295 is resolved. I don't think there's much pressure for us to get this working since we already have Chocolatey as an option so I think it would be nice to just wait for GoReleaser to sort it out.

**Comment by jimaek** [comment]
Ok. No hurry, I think Winget is mostly for branding purposes so we can wait as long as needed

**Comment by jimaek** [comment]
Looks like someone requested it and it will get added https://github.com/microsoft/winget-pkgs/pull/111495

**Comment by jimaek** [comment]
Its now supported https://goreleaser.com/customization/winget/?h=winget
