### ISSUE TITLE
Add auth support via ENV

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#42]
To support our upcoming API keys we need a few changes:
- ~~New parameter -T/--token (open to different options)~~ - in #108
- ENV VAR support to allow the user to set it on a shell or script level. `GLOBALPING_TOKEN`
- ~~New command `limits` that will output IP limits if the user is anon and remaining credits if the user is authenticated~~ - in #109

**Comment by MartinKolarik** [comment]
@radulucut let's start by adding support for `GLOBALPING_TOKEN`, and I'll specify the rest of the interface to add a little later. The token is sent as `Authorization: Bearer YOUR-TOKEN` ([docs](https://www.jsdelivr.com/docs/api.globalping.io#overview)). You can ping me by Slack/mail, and I'll send you some actual tokens for testing.
