### ISSUE TITLE
Incorrect packaging of .rpm

### ISSUE THREAD

**Issue by perosb** [jsdelivr/globalping-cli#48]
After installing version 1.0.0 (I haven't tested any other version) the `globalping` command cannot be found.

```
drwxr-xr-x.  15 root root    4096 15 nov 15.55  usr
-rwxr-xr-x.   1 root root 8355840 11 apr 19.40 '\usr\bin\globalping'
drwxr-xr-x.  21 root root    4096 15 nov 16.02  var
```
```
/tmp$ rpm -qlp ./globalping-1.0.0-1.x86_64.rpm 
\usr\bin\globalping
```

**Comment by jimaek** [comment]
How did you install it? Using the RPM script? And what OS are you using?

**Comment by perosb** [comment]
Was just about to update ;)

I used the commands from README https://github.com/jsdelivr/globalping-cli#centosfedorarocky-linuxalmalinux-rpm

I also downloaded the package manually for f37 and verified with "rpm -qlp"
`wget --content-disposition "https://packagecloud.io/jsdelivr/globalping/packages/fedora/37/globalping-1.0.0-1.x86_64.rpm/download.rpm?distro_version_id=260"`

**Comment by jimaek** [comment]
Looks like incorrect encoding of the path, try this command:

`mv '\usr\bin\globalping' /usr/bin/globalping`

It should fix it and I'll look into why its happening

**Comment by perosb** [comment]
0.4.0 seems to be correct https://packagecloud.io/jsdelivr/globalping/packages/fedora/37/globalping-0.4.0-1.x86_64.rpm?distro_version_id=260

Also .deb are fine.

**Comment by jimaek** [comment]
Looks like goreleaser 1.17 is broken. I downgraded and everything seems normal now. Check the 1.0.1 release please.
Sorry for this bad experience and let me know if you find anything else that we could improve one/
