### ISSUE TITLE
Add install probe command

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#5]
Something like 

globalping install-probe

And it would check if Docker is installed. If not exit and show a message asking to install it with proper instructions for the OS.
If Docker is installed, it would ask for confirmation to pull and start a Docker container. Y/n.
If user selects yes then we run 
```
docker run -d --network host --restart=always --name globalping-probe ghcr.io/jsdelivr/globalping-probe
docker ps
```

correct commands here https://github.com/jsdelivr/globalping-probe

**Comment by jimaek** [comment]
@didil What do you think? Is it realistic? It would have to work on linux/macos/windows and note sure if running other binaries before exiting requires special permissions or not

**Comment by didil** [comment]
@jimaek I think if docker is installed and the user running the tool is allowed to run docker commands it should work. We would need to test it of course.

**Comment by didil** [comment]
@jimaek is this something we can start working on ?

**Comment by jimaek** [comment]
Yes lets try this task. I think the main problem will be to make the detection work properly on linux/windows/macos. Plus there is this whole thing of docker vs docker.io vs podman.

e.g. podman requires a different command to run and docker is often an alias to podman
