### ISSUE TITLE
Add --share option

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#53]
When enabled at the end of the output also show the website URL https://www.jsdelivr.com/globalping/id=$id (exact format to be updated) that will contain the same results in case the user wants to visualize them on the map.

**Comment by MartinKolarik** [comment]
Link format: `https://www.jsdelivr.com/globalping?measurement=$id`

We can probably use a similar style for the message as we have for probe location, e.g.:
```
> You can also view the results at https://www.jsdelivr.com/globalping?measurement=$id
```

It should be printed to `stderr`.

**Comment by jimaek** [comment]
> ```
> > You can also view the results at https://www.jsdelivr.com/globalping?measurement=$id
> ```
> 
> It should be printed to `stderr`.

Maybe just `> https://www.jsdelivr.com/globalping?measurement=$id` to make it easier to parse?

Also where do we show that line? At the very end of all output?

**Comment by MartinKolarik** [comment]
At the very end, in the same color as the location. It isn't meant to be parsed so I suggest keeping the text to make the purpose clear (especially if we decide to show it always but even if not).

**Comment by jimaek** [comment]
Ok then. I guess if the user wants to get the ID he can use the JSON output.

> Link format: `https://www.jsdelivr.com/globalping?measurement=$id`
> 
> We can probably use a similar style for the message as we have for probe location, e.g.:
> 
> At the very end, in the same color as the location.
> ```
> > View the results online https://www.jsdelivr.com/globalping?measurement=$id
> ```
> 
> It should be printed to `stderr`.

**Comment by didil** [comment]
@jimaek do we need to add an empty line between the results and the 
`> View the results online: https://www.jsdelivr.com/globalping?measurement=$id` line ?

**Comment by jimaek** [comment]
Probably not? Since it has the color difference and prefix

**Comment by MartinKolarik** [comment]
Yes, let's try without.
