### ISSUE TITLE
Improve HTTP output

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-cli#55]
Instead of `rawOutput`, print `rawHeaders` to `stderr` and `rawBody` to `stdout` (see https://github.com/jsdelivr/globalping/issues/347 for explanation).

**Comment by MartinKolarik** [comment]
For HEAD, nothing changes. For GET, you get the headers + body now. We could add an option to remove headers from the output but I don't think it's necessary when it goes to the error stream.

**Comment by didil** [comment]
@MartinKolarik does this only need to be implemented for ci mode ? or also for the live mode ?

**Comment by didil** [comment]
also where do we write the result headers (example `> EU, DE, Frankfurt, ASN:16276, OVH SAS)`). To stderr or stdout ?

**Comment by MartinKolarik** [comment]
> @MartinKolarik does this only need to be implemented for ci mode ? or also for the live mode ?

Always.


> also where do we write the result headers (example > EU, DE, Frankfurt, ASN:16276, OVH SAS)). To stderr or stdout ?

err, I already opened a separate task for that as it applies to all commands #56

**Comment by didil** [comment]
@jimaek do these changes `--full` and `rawBody` vs `rawOutput` need to be implemented in the chatbot as well ?

**Comment by MartinKolarik** [comment]
@didil yes make chatbots match the CLI.
