### ISSUE TITLE
Improve output handling

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-cli#56]
Related to #55. We currently print the API response itself and some additional information. The extra information should always go to `stderr`. For example:

```
$ globalping http https://cdn.jsdelivr.net/npm --method GET
> NA, US, (FL), Tampa, ASN:29802, HIVELOCITY, Inc.
Invalid URL. The URL structure is /npm/package@version/file.js
```

The first line should go to `stderr` and the second to `stdout`. This makes it easier to programmatically process just one part of the output and matches how other CLIs work. If someone wants both parts, they can still merge it via `2>&1`.

**Comment by jimaek** [comment]
The output itself doesn't change in this case right?

**Comment by MartinKolarik** [comment]
No, but running `globalping http https://cdn.jsdelivr.net/npm --method GET > file` means you only get the second line in the output and the first stays in the terminal.

**Comment by MartinKolarik** [comment]
Note that this makes processing the output easier for the most common `--limit 1` scenario, but it's still tricky as soon as there are multiple responses. Some research would be useful to see how other tools handle this problem. Current ideas:
 - allow the user to specify an output directory, then write each response to a separate file in the directory,
 - print some kind of separator between the responses,
 - do nothing and let users handle this case by using `--json | jq` ?

**Comment by didil** [comment]
I believe PR #58 fixes this as the results separator `> NA, US ...` now goes to stderr
