### ISSUE TITLE
Missing body in HTTP tests

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#59]
- The missing body/html seems to be an issue with the globalping probes specific to www.jsdelivr.com. If you try with `https://www.google.com` for example it doesn't happen. I tried a manual api request to globalping for http get jsdeliver.com and here is the full output of a "result", there is no "rawBody". That's why there is no body/html in the output 

`{
  "status": "failed",
  "resolvedAddress": "78.111.103.62",
  "headers": {
    "server": "nginx",
    "date": "Mon, 01 May 2023 10:40:48 GMT",
    "content-type": "text/html; charset=utf-8",
    "transfer-encoding": "chunked",
    "connection": "close",
    "vary": "Accept-Encoding, Accept-Encoding",
    "cf-ray": "7bf17ec31d06b742-AMS",
    "cache-control": "public, max-age=300, must-revalidate, stale-while-revalidate=600, stale-if-error=86400",
    "etag": "W/\"ae82-pgsQqvPwyIeqFA+gNk2fTj71qs0\"",
    "link": "<https://www.jsdelivr.com/>; rel=\"canonical\"",
    "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
    "cf-cache-status": "DYNAMIC",
    "x-render-origin-server": "Render",
    "x-response-time": "28ms",
    "set-cookie": [
      "__cf_bm=FdOmrLqHM3qkZuOKOXqtpSynwwwT.OAFWzIUlptVaTY-1682707871-0-ASc3+lm3OMmedlRZAZmQlkFCxMrvb1hp/6+t0KnYaEcMADH4l9AhMqrh7GXyQ37hd8apEWJRFG2ePxNf0rZjFrw=; path=/; expires=Fri, 28-Apr-23 19:21:11 GMT; domain=.onrender.com; HttpOnly; Secure; SameSite=None"
    ],
    "cache": "HIT, HIT",
    "x-cached-since": "2023-04-28T18:51:11+00:00, 2023-05-01T10:36:17+00:00",
    "x-id": "am3-up-gc88, wbs-up-gc4",
    "x-nginx": "nginx-be, nginx-be",
    "content-encoding": "br"
  },
  "rawHeaders": "Server: nginx\nDate: Mon, 01 May 2023 10:40:48 GMT\nContent-Type: text/html; charset=utf-8\nTransfer-Encoding: chunked\nConnection: close\nVary: Accept-Encoding\nCF-Ray: 7bf17ec31d06b742-AMS\nCache-Control: public, max-age=300, must-revalidate, stale-while-revalidate=600, stale-if-error=86400\nETag: W/\"ae82-pgsQqvPwyIeqFA+gNk2fTj71qs0\"\nLink: <https://www.jsdelivr.com/>; rel=\"canonical\"\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\nVary: Accept-Encoding\nCF-Cache-Status: DYNAMIC\nx-render-origin-server: Render\nx-response-time: 28ms\nSet-Cookie: __cf_bm=FdOmrLqHM3qkZuOKOXqtpSynwwwT.OAFWzIUlptVaTY-1682707871-0-ASc3+lm3OMmedlRZAZmQlkFCxMrvb1hp/6+t0KnYaEcMADH4l9AhMqrh7GXyQ37hd8apEWJRFG2ePxNf0rZjFrw=; path=/; expires=Fri, 28-Apr-23 19:21:11 GMT; domain=.onrender.com; HttpOnly; Secure; SameSite=None\nCache: HIT\nX-Cached-Since: 2023-04-28T18:51:11+00:00\nX-ID: am3-up-gc88\nX-NGINX: nginx-be\nContent-Encoding: br\nCache: HIT\nX-Cached-Since: 2023-05-01T10:36:17+00:00\nX-ID: wbs-up-gc4\nX-NGINX: nginx-be",
  "rawBody": null,
  "statusCode": 200,
  "statusCodeName": "OK",
  "timings": {
    "total": 128,
    "download": 6,
    "firstByte": 17,
    "dns": 89,
    "tls": 13,
    "tcp": 3
  },
  "tls": {
    "authorized": true,
    "createdAt": "2023-02-18T00:00:00.000Z",
    "expiresAt": "2024-02-18T23:59:59.000Z",
    "issuer": {
      "C": "GB",
      "ST": "Greater Manchester",
      "L": "Salford",
      "O": "Sectigo Limited",
      "CN": "Sectigo RSA Domain Validation Secure Server CA"
    },
    "subject": {
      "CN": "jsdelivr.com",
      "alt": "DNS:jsdelivr.com, DNS:data.jsdelivr.com, DNS:www.jsdelivr.com"
    }
  },
  "rawOutput": ""
}`

_Originally posted by @didil in https://github.com/jsdelivr/globalping-cli/issues/58#issuecomment-1529568956_

**Comment by didil** [comment]
@jimaek I don't think the duplication is related to the missing body

**Comment by jimaek** [comment]
@MartinKolarik any ideas why the API is missing the body for jsdelivr.com?

**Comment by MartinKolarik** [comment]
Closing as this is a GP issue, but later we'll also need to improve the client-side handling of probe failures since the response here says ` "status": "failed"`. I'll specify how later in #61.
