### ISSUE TITLE
HTTP all not working

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#65]
We deployed the latest API changes. I have now pulled the CLI master but some things are missing?

- I dont see the option http --full that we agreed on
- default HTTP GET shows both headers and body

Am I doing something wrong?

**Comment by MartinKolarik** [comment]
Both work for me on master.

**Comment by didil** [comment]
@jimaek are you on the master branch ? could you please share the output of `git log` ?
There shouldn't be any cache to purge in this case

**Comment by jimaek** [comment]
```
# git branch
  improve-http-output
  install-probe
* master
  output-jumps
```

```
commit 0cf5972c05f14e19fa3f8891c0a99d93f194d3db (HEAD -> master, origin/master, origin/HEAD)
Merge: e081f12 74a230c
Author: Dmitriy Akulov <dakulovgr@gmail.com>
Date:   Thu Apr 6 14:35:26 2023 +0100

    Merge pull request #34 from didil/http-fixes

    HTTP fixes/refactor

commit 74a230c83644d5ced1477546a2149621bda67e56 (origin/http-fixes)
Author: didil <1284255+didil@users.noreply.github.com>
Date:   Thu Apr 6 14:09:34 2023 +0100

    http fixes/refactor

commit e081f12a4a93e667cb37fdbd91c5fcb30991d987
Author: Dmitriy Akulov <dakulovgr@gmail.com>
Date:   Tue Mar 21 14:06:34 2023 +0100

    cdn icon
```

**Comment by jimaek** [comment]
rm -rf and cloning again fixed it. The only remaining issue is the duplicating output which literally happens on every single HTTP GET request now. HEAD and other tests dont have this issue.
