### ISSUE TITLE
Add ISP name and Cloud regions to output

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#7]
Something like this:

```
> EU, PL, Warsaw, ASN:5617, Orange Polska
> EU, PL, Warsaw, ASN:222, Google Cloud Inc, eu-west-1   (only if it exists, dont show null)
```

To both CLI and Slack app

**Comment by ayuhito** [comment]
Regarding #236, are we going to guarantee the cloud region tag will always be the first element in the tags array if there are multiple elements? I don't think we want to include any other tags like `5g-connection` or `u-random-tag`, correct?

My other concern I have regarding system tags is that for probes with no region tag but may have an admin tag like `5g-connection`, I wouldn't be able to filter that out from the output if we're using the first element logic. I would need a prepopulated list of admin tags to filter out.

**Comment by ayuhito** [comment]
We only check for regions for AWS and GCP. Both end in numbers so that validation step works. e.g. `aws-eu-west-2` or `gcp-europe-west2`

Would we then be fine limiting admin tags to not end in a number suffix unless we want it to show up on the CLI?

**Comment by jimaek** [comment]
Yes I can't imagine why an admin tag would end in a number
