### ISSUE TITLE
Automate addition of new OS releases

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#77]
The list of supported OS is currently static and requires manual updates https://github.com/jsdelivr/upload-packagecloud/blob/main/push.sh

We should automate this

**Comment by didil** [comment]
@jimaek what do you mean by "automating" in this case ? Like a process running somewhere that will check OS releases periodically and create a Github PR to modify the push.sh file in the jsdelivr/upload-packagecloud repository ?

**Comment by jimaek** [comment]
No something simpler, for example pulling a list from an outside source right in that script. It sounds like a common issue so I think these lists must exist

**Comment by radulucut** [comment]
@jimaek it seems that we can use `deb/any` and  `rpm/rpm_any` instead of providing a specific list. Should I go for it or stick with the predefined list?
Btw, we can get the list from here: https://packagecloud.io/docs/api#resource_distributions_method_index

**Comment by jimaek** [comment]
> @jimaek it seems that we can use `deb/any` and `rpm/rpm_any` instead of providing a specific list.

If this works then lets use that, as long as it doesnt break anything
