### ISSUE TITLE
Latency parameter

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#8]
How about a global parameter called --latency. If added then instead of the normal rendered output we only return the latency numbers.

- Ping: `"avg": 0.713,`
- Traceroute: dont support
- DNS: `"timings": {          "total": 4`
- MTR: `"stats": {              "avg": 0.8,`
- HTTP: `"timings": {          "total": 246,`

The idea is that if you want to benchmark an endpoint from 20 locations you dont need all the output, you just need the numbers

**Comment by ayuhito** [comment]
@jimaek, to clarify. Something like this?

![image](https://user-images.githubusercontent.com/38220115/219767955-f33ecc9b-9e51-4f18-bbee-8ed13835388f.png)

**Comment by jimaek** [comment]
Yes, but probably only the first 3 values. The rest seems not as useful if you only care about running a quick latency test
