### ISSUE TITLE
Detect output redirect

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#9]
https://rderik.com/blog/identify-if-output-goes-to-the-terminal-or-is-being-redirected-in-golang/

Currently a command like this `globalping ping gcore.com --from Orange+Poland -L 2 --packets 5 > file` creates a useless file that cant be read. 

It would be nice to detect if the user is redirecting the output and instead it wrote the results in the same way they appear in the terminal at the very end.

**Comment by ayuhito** [comment]
I think it's fine if we leave it as `--ci` if we document its usecase. It's pretty common in other CLIs. and a niche requirement. Not a big fan of `--no-realtime`.

**Comment by jimaek** [comment]
Ok sure, I am fine with --ci as long as its clear that its not just for CI but also for general scripting
